name: Build - linux
on: 
  push:
    branches:
      - '**'
    tags:
      - 'v*'
    paths-ignore:
      - 'buildtools/docker/**'
      - 'docs/**'
      - '.vscode/**'
      - '.devcontainer/**'

jobs:
  build-debian10:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wangyoucao577/ffmpeg-build/linux-debian10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
          
      - name: Build
        run: |
          buildtools/scripts/build.sh
          tree build

      - uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-bin-debian10
          path: build/bin/

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ffbuild-logs-debian10
          path: ffmpeg/ffbuild/config.log

  test-debian10:
    needs: build-debian10
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wangyoucao577/ffmpeg-build/linux-debian10
    steps:
      - uses: actions/checkout@v3
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Test
        run: |
          FFMPEG_BIN_PATH=ffmpeg-bin-debian10
          tree ${FFMPEG_BIN_PATH}
          chmod +x ${FFMPEG_BIN_PATH}/*
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -threads 1 -i ./tests/small_bunny_1080p_60fps.mp4 -c:v libsvtav1 -c:a copy out.mp4
          # ./${FFMPEG_BIN_PATH}/ffmpeg -y -threads 1 -i ./tests/small_bunny_1080p_60fps.mp4 -c:v libaom-av1 -c:a copy out.mp4
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -threads 1 -i ./tests/small_bunny_1080p_60fps.mp4 -c:v libx264 -c:a libopus out.mp4
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -i out.mp4 -i ./tests/small_bunny_1080p_60fps.mp4 -lavfi "libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path=./${FFMPEG_BIN_PATH}/vmaf_v0.6.1.json" -f null -
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -threads 1 -i ./tests/small_bunny_1080p_60fps.mp4 -c:v libx265 -c:a libfdk_aac out_hevc.mp4
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -i out_hevc.mp4 -c copy out_hevc.flv
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -i out_hevc.flv -c copy out_hevc2.mp4
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -i ./tests/small_bunny_1080p_60fps.mp4 -vf drawtext="text='hello world':fontfile=./${FFMPEG_BIN_PATH}/FreeSans.ttf" -f null -
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -i ./tests/small_bunny_1080p_60fps.mp4 -vf subtitles=./tests/sintel_en.srt -f null -

  build-debian11:
    strategy:
      matrix:
        build_type: [debug, release]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wangyoucao577/ffmpeg-build/linux-debian11
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
          
      - name: Build
        run: |
          export FFMPEG_BUILD_TYPE=${{ matrix.build_type }}
          buildtools/scripts/build.sh
          tree build

      - uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-bin-debian11-${{ matrix.build_type }}
          path: build/bin/
          
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ffbuild-logs-${{ matrix.build_type }}
          path: ffmpeg/ffbuild/config.log

  test-debian11:
    strategy:
      matrix:
        build_type: [debug, release]
    needs: build-debian11
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wangyoucao577/ffmpeg-build/linux-debian11
    steps:
      - uses: actions/checkout@v3
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Test
        run: |
          FFMPEG_BIN_PATH=ffmpeg-bin-debian11-${{ matrix.build_type }}
          tree ${FFMPEG_BIN_PATH}
          chmod +x ${FFMPEG_BIN_PATH}/*
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -threads 1 -i ./tests/small_bunny_1080p_60fps.mp4 -c:v libsvtav1 -c:a copy out.mp4
          # ./${FFMPEG_BIN_PATH}/ffmpeg -y -threads 1 -i ./tests/small_bunny_1080p_60fps.mp4 -c:v libaom-av1 -c:a copy out.mp4
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -threads 1 -i ./tests/small_bunny_1080p_60fps.mp4 -c:v libx264 -c:a libopus out.mp4
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -i out.mp4 -i ./tests/small_bunny_1080p_60fps.mp4 -lavfi "libvmaf=log_fmt=xml:log_path=/dev/stdout:model_path=./${FFMPEG_BIN_PATH}/vmaf_v0.6.1.json" -f null -
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -threads 1 -i ./tests/small_bunny_1080p_60fps.mp4 -c:v libx265 -c:a libfdk_aac out_hevc.mp4
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -i out_hevc.mp4 -c copy out_hevc.flv
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -i out_hevc.flv -c copy out_hevc2.mp4
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -i ./tests/small_bunny_1080p_60fps.mp4 -vf drawtext="text='hello world':fontfile=./${FFMPEG_BIN_PATH}/FreeSans.ttf" -f null -
          ./${FFMPEG_BIN_PATH}/ffmpeg -y -i ./tests/small_bunny_1080p_60fps.mp4 -vf subtitles=./tests/sintel_en.srt -f null -
