name: Build - ios

on: 
  push:
    branches:
      - '**'
    tags:
      - 'v*'
    paths-ignore:
      - 'buildtools/docker/**'
      - 'docs/**'
      - '.vscode/**'
      - '.devcontainer/**'
      - '**.md'

env:
  CONAN_PRINT_RUN_COMMANDS: 1

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        build_profiles: ["ios-armv7", "ios-armv8", "ios-simulator-x86_64"] 
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'

      # setup build tools: ninja, conan, yasm
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: turtlebrowser/get-conan@main
        with:
          version: 1.62.0
      - name: Install and check tools
        run: |
          brew install tree bear automake  
          conan --version && ninja --version && echo $PATH

      # build
      - name: Build
        run: | 
          cd buildtools/conan
          conan create -pr profiles/${{ matrix.build_profiles }} openssl
          conan create -pr profiles/${{ matrix.build_profiles }} boringssl

      # view built conan packages
      - name: View built packages
        run : |
          conan search "*"
