name: Build - linux
on: 
  push:
    branches:
      - '**'
    tags:
      - 'v*'
    paths-ignore:
      - 'buildtools/docker/**'
      - 'docs/**'
      - '.vscode/**'
      - '.devcontainer/**'
      - '**.md'

jobs:
  build-debian10:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wangyoucao577/ffmpeg-build/linux-debian10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
          
      - name: Build
        run: |
          buildtools/scripts/build.sh
          tree build

      - uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-bin-debian10
          path: build/bin/

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ffbuild-logs-debian10
          path: ffmpeg/ffbuild/config.log

  test-debian10:
    needs: build-debian10
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wangyoucao577/ffmpeg-build/linux-debian10
    steps:
      - uses: actions/checkout@v3
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Test
        run: |
          export FFMPEG_BIN_PATH=ffmpeg-bin-debian10
          ./tests/acceptance-test.sh

  build-debian11:
    strategy:
      matrix:
        build_type: [debug, release]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wangyoucao577/ffmpeg-build/linux-debian11
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
          
      - name: Build
        run: |
          export FFMPEG_BUILD_TYPE=${{ matrix.build_type }}
          buildtools/scripts/build.sh
          tree build

      - uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-bin-debian11-${{ matrix.build_type }}
          path: build/bin/
          
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ffbuild-logs-${{ matrix.build_type }}
          path: ffmpeg/ffbuild/config.log

  test-debian11:
    strategy:
      matrix:
        build_type: [debug, release]
    needs: build-debian11
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/wangyoucao577/ffmpeg-build/linux-debian11
    steps:
      - uses: actions/checkout@v3
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Test
        run: |
          export FFMPEG_BIN_PATH=ffmpeg-bin-debian11-${{ matrix.build_type }}
          ./tests/acceptance-test.sh
